### Site Settings ###
title: Agusti Gunawan
description: >-
  Fueled by a love for innovation and a cup of coffee, 
  I thrive in crafting digital solutions that seamlessly blend functionality and user experience.
baseurl: "" # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository: agustig/portfolio # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
# remote_theme: YoussefRaafatNasry/portfolYOU
open_new_tab: true

### Plugins ###
plugins:
  - jemoji

### Navbar Settings ###
nav_exclude: # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**
  - documentation/**

### Author Info ###
author:
  name: Agusti Gunawan
  image: https://avatars.githubusercontent.com/u/19257819?s=400&u=c169a7a00715d3ccba8df67dae16de7c808c3499&v=4
  # behance           : your_username
  # dribbble          : your_username
  email: hellowork@agustig.dev
  facebook: agusti.gunawan
  github: agustig
  # gitlab            : your_username
  instagram: agusti.gunawan
  # kaggle            : your_username
  linkedin: agustigunawan
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username

### Posts ###
permalink: /blog/:title

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements: # For Documentation Only
    output: true # For Documentation Only

### Disqus ###
disqus:
  shortname: your-short-name-disqus # Your website Shortname on disqus

### Analytics ###
analytics:
  enabled: false # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
